### ISSUE TITLE
Adding AUTH_KEY to header of API call

### ISSUE THREAD

**Issue by NiqueDaSneak** [fvdm/nodejs-pastecapi#12]
I don't see anywhere in the documentation a place for one to do that. When I try the ping function the response that I get back is that I am missing the AUTH_KEY which is of course true because I never define it anywhere. Any help with this @fvdm ?

**Comment by fvdm** [comment]
Hi @NiqueDaSneak I think that is an undocumented feature. I'm looking into this now.

**Comment by fvdm** [comment]
I'll check it out tommorow, can't get Pastec daemon working with `--authkey`

**Comment by NiqueDaSneak** [comment]
Thank you so much. I was having trouble so I figured I'd reach out.

**Comment by fvdm** [comment]
I implemented authkey support in v1.2.0 which I just published on npm.

You can set your auth key like this:

```js
var pastec = require ('pastecapi') ('https://endpoint...', 'your auth key');
```

**Comment by NiqueDaSneak** [comment]
This is great!!

**Comment by NiqueDaSneak** [comment]
Will this implementation I receive an error that says misformmated request.
That doesn't seem right when I am just using the ping function just as you
illustrate in the readme.

**Comment by fvdm** [comment]
Yeah I'm fixing this, but I have not enough time today

**Comment by NiqueDaSneak** [comment]
Awesome. Just making sure I'm not making a silly error. Thanks for
everything!

**Comment by fvdm** [comment]
It turns out the Hosted API does not support `ping`.

The fix is not complete yet, but if you install from `develop` branch the other methods (not ping) should work ok for now.

`npm install fvdm/nodejs-pastecapi#develop`

**Comment by fvdm** [comment]
@NiqueDaSneak Alright I finally published the updated version with Index ID and Authkey support. Just run `npm i pastecapi` to get it.

```js
var pastec = require ('pastecapi') ({
  endpoint: 'https://api.pastec.io',
  indexid: 'your index id',
  authkey: 'your auth key'
});

pastec.searchIndex ('/path/to/image.jpg', console.log);
// and so on
```
